--CREACION DE LA BASE DE DATOS
CREATE DATABASE DBNEONET;

USE DBNEONET;

--CREACION DE TABLAS 
CREATE TABLE PRODUCTOS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    STOCK INT NOT NULL
);

CREATE TABLE CLIENTES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE
);


CREATE TABLE VENTAS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    FECHA DATETIME NOT NULL DEFAULT GETDATE(),
    CLIENTE_ID INT NOT NULL
);
--- LLAVE FORANEAS
ALTER TABLE VENTAS ADD CONSTRAINT FK_VENTAS_CLIENTES FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID);



CREATE TABLE DETALLEVENTA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    VENTA_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL
);
-- LLAVE FORANEA
ALTER TABLE DETALLEVENTA ADD CONSTRAINT FK_DETALLEVENTA_VENTAS FOREIGN KEY (VENTA_ID) REFERENCES VENTAS(ID);
ALTER TABLE DETALLEVENTA ADD CONSTRAINT FK_DETALLEVENTA_PRODUCTOS FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID);




