USE DBNEONET;

--INSERT A TABLA DE PRODUCTOS
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, STOCK) VALUES ('LAPTOP HP', 5500.00, 10);
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, STOCK) VALUES ('MOUSE LOGITECH', 150.00, 50);
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, STOCK) VALUES ('TECLADO MECANICO LOGITECH', 300.00, 30);
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, STOCK) VALUES ('MONITOR HP 24''', 1200.00, 15);


INSERT INTO CLIENTES (NOMBRE, EMAIL) VALUES ('JOSE LOPEZ', 'JOSE@GMAIL.COM');
INSERT INTO CLIENTES (NOMBRE, EMAIL) VALUES ('CARLA ARMANDO', 'CARLA@GMAIL.COM');
INSERT INTO CLIENTES (NOMBRE, EMAIL) VALUES ('INES CARRILLO', 'INES@GMAIL.COM');


INSERT INTO VENTAS (FECHA, CLIENTE_ID) VALUES (GETDATE(), 1);
INSERT INTO VENTAS (FECHA, CLIENTE_ID) VALUES (GETDATE(), 2);
INSERT INTO VENTAS (FECHA, CLIENTE_ID) VALUES (GETDATE(), 1);
INSERT INTO VENTAS (FECHA, CLIENTE_ID) VALUES (GETDATE(), 3);


INSERT INTO DETALLEVENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD, PRECIO_UNITARIO) 
VALUES (1, 1, 1, 5500.00);

INSERT INTO DETALLEVENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD, PRECIO_UNITARIO) 
VALUES (1, 2, 2, 150.00);

INSERT INTO DETALLEVENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD, PRECIO_UNITARIO) 
VALUES (2, 3, 1, 300.00);

INSERT INTO DETALLEVENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD, PRECIO_UNITARIO) 
VALUES (3, 4, 1, 1200.00);

INSERT INTO DETALLEVENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD, PRECIO_UNITARIO) 
VALUES (4, 2, 3, 150.00);

INSERT INTO DETALLEVENTA (VENTA_ID, PRODUCTO_ID, CANTIDAD, PRECIO_UNITARIO) 
VALUES (4, 3, 2, 300.00);


SELECT * FROM PRODUCTOS;

SELECT * FROM CLIENTES;

SELECT * FROM VENTAS;

SELECT * FROM DETALLEVENTA;

